export const DEMO_DATA = {
  profiles: [
    {
      id: "demo-author-1",
      displayName: "春灯",
      bio: "夕方と教室をよく書きます。",
      createdAt: "2026-06-12T09:00:00.000Z",
    },
    {
      id: "demo-author-2",
      displayName: "水脈",
      bio: "短い詩と雨の描写が多めです。",
      createdAt: "2026-06-13T09:00:00.000Z",
    },
    {
      id: "demo-author-3",
      displayName: "群青",
      bio: "散文詩を置いています。",
      createdAt: "2026-06-14T09:00:00.000Z",
    },
  ],
  poems: [
    {
      id: "demo-poem-1",
      authorId: "demo-author-1",
      title: "放課後の窓",
      genre: "自由詩",
      tags: ["学校", "夕方"],
      body: "窓を閉めたあとも\n机の木目には まだ西日の粉が残っていて\n帰る支度だけが 先に廊下へ出ていく\n\n黒板の端で欠けた白い線は\n言いそびれた返事みたいに\n誰にも消されないまま\n教室の温度を少しだけ引き止めている",
      createdAt: "2026-06-20T08:30:00.000Z",
      updatedAt: "2026-06-20T08:30:00.000Z",
    },
    {
      id: "demo-poem-2",
      authorId: "demo-author-2",
      title: "六月の駅",
      genre: "短詩",
      tags: ["雨", "朝"],
      body: "濡れたホームで\n傘の先から落ちる音だけが\n先に改札を抜けていく",
      createdAt: "2026-06-18T22:00:00.000Z",
      updatedAt: "2026-06-18T22:00:00.000Z",
    },
    {
      id: "demo-poem-3",
      authorId: "demo-author-3",
      title: "紙コップの海",
      genre: "散文詩",
      tags: ["昼休み", "比喩"],
      body: "昼休みの自販機前で受け取った紙コップは、思っていたよりずっと軽かった。軽いものほど、たぶん、持っている人の顔をよく映す。飲み口の縁に浮いた泡を見ているうちに、きのう失くした言葉が、あれもただの炭酸だったのではないかと思えてくる。飲み干したあと、底に残る白さだけが、午後の授業の静けさを知っている。",
      createdAt: "2026-06-16T05:15:00.000Z",
      updatedAt: "2026-06-16T05:15:00.000Z",
    },
  ],
  comments: [
    {
      id: "demo-comment-1",
      poemId: "demo-poem-1",
      authorId: "demo-author-2",
      body: "最後の二行が静かで印象的でした。",
      createdAt: "2026-06-20T12:10:00.000Z",
    },
    {
      id: "demo-comment-2",
      poemId: "demo-poem-1",
      authorId: "demo-author-3",
      body: "教室の残り香が見えるようでした。",
      createdAt: "2026-06-20T14:20:00.000Z",
    },
    {
      id: "demo-comment-3",
      poemId: "demo-poem-3",
      authorId: "demo-author-1",
      body: "比喩の置き方がきれいです。",
      createdAt: "2026-06-16T10:40:00.000Z",
    },
  ],
  likes: [
    { poemId: "demo-poem-1", userId: "demo-author-2" },
    { poemId: "demo-poem-1", userId: "demo-author-3" },
    { poemId: "demo-poem-2", userId: "demo-author-1" },
    { poemId: "demo-poem-3", userId: "demo-author-1" },
    { poemId: "demo-poem-3", userId: "demo-author-2" },
  ],
};
